version: "3.8"

services:
  php:
    container_name: mezzioapp_php
    build:
      context: ./etc/php-apache
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/mezzioapp
    working_dir: /var/www/mezzioapp
    ports:
      - 9000:80
    depends_on:
      - mysql
      - composer

  composer:
    image: composer:2.0
    command: install
    volumes:
      - .:/app

  mysql:
    container_name: mezzioapp_mysql
    image: mysql:8.0
    ports:
      - 9002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./etc/database:/docker-entrypoint-initdb.d:ro
